image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-onboard"
env:
  es_host: "{{ groups['elasticsearch'][0] }}"
  audit_index: "hcx_audit"
  audit_alias: "hcx_audit"
  registry_basePath: "http://hcx-registry.{{ env }}.svc.cluster.local:8081"
  registry_hcx_code: "{{ registry_hcx_code }}"
  not_allowed_urls: {{ gateway_not_allowed_urls }}
  hcx_instance_name: {{ hcx_instance_name }}
  aws_accessKey: {{ aws_accessKey }}
  aws_accessSecret: {{ aws_accessSecret }}
  aws_region: {{ aws_region }}
  email_id: {{ email_id }}
  email_pwd: {{ email_pwd }}
  postgres_url: "jdbc:postgresql://{{ hcx_api_postgresql_host }}/postgres"
  postgres_user: "{{ hcx_api_postgresql_user }}"
  postgres_password: "{{ hcx_api_postgresql_password }}"
  HCX_API_BASEPATH : http://hcx-api.{{ env }}.svc.cluster.local:8080
  ENV: {{ env }}
  private_key: {{ hcx_private_key }}
  

service:
  type: ClusterIP
