apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  location.list: |-
{{ .Values.location_list | indent 4 }}
  sites.conf: |-
{{ .Values.sites_conf | indent 4 }}