name: Deploy HCX Demo app
on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Build Cluster'
        required: true
        default: 'true'
      namespace:
        description: 'Build ENV'
        required : true
        default: 'true'
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name : path check
        run : pwd
