name: Deploy worflow for HCX API.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Cluster Environment
        default: dev
        required: true
# on:
#   push:
#     branches:
#     - master
#     - staging
#     - workflow
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        # aws-profile: hcx
        # role-to-assume: arn:aws:iam::131795456882:role/OrganizationAccountAccessRole
    # - uses: actions/checkout@v1

    # - name: Checkout Private Repo
    #   run: |
    #     eval `ssh-agent -s`
    #     ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
    # - uses: actions/checkout@v1  
    #   with:
    #     repository: organization_name/repo_name
    #     token: ${{ secrets.ACCESS_TOKEN }}


    # - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository. 
    #   with:
    #     ssh-private-key: |
    #       ${{ secrets.SSH_PRIVATE_KEY }}
    #     repo-mappings: |
    #       github.com/Swasth-Digital-Health-Foundation/DevOps


    # - uses: actions/checkout@v2
    #   with:
    #     submodules: recursive

    # - name: Check file structure
    #   run: ls -lrt ${{ github.workspace }}







    - name: Checkout private 
      uses: actions/checkout@v3
      with:
        # repository: Swasth-Digital-Health-Foundation/DevOps
        repository: Swasth-Digital-Health-Foundation/DevOps
        ref: 'workflow'
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive
        path: DevOps
      
    - name: Pull image tag from S3 bucket
      run: |
        aws s3 cp s3://build-tags/tag.txt /tmp/tag.txt
        export IMAGE_TAG="$(cat /tmp/tag.txt)"

    - name: 'Deploy'
      uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
      # uses: vimeda/helm@v1.6.8
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region: ap-south-1
        # aws-profile: git-deploy
        cluster-name: ${{ github.event.inputs.environment }}-cluster
        name: 'hcx-api'
        namespace: '${{ github.event.inputs.environment }}'
        # release: hcx-api
        chart-path: 'application/helm/core/hcx-api/'
        config-files: 'application/helm/core/hcx-api/values.yaml, DevOps/hcx/ansible/inventory/${{ github.event.inputs.environment }}/group_vars/${{ github.event.inputs.environment }}.yaml'
        values: |
          image.tag=${{ env.IMAGE_TAG }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

###


