name: Deploy workflow for NotificationsJob.

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Cluster Environment
        default: dev
        required: true
# on:
#   push:
#     branches:
#     - master
#     - staging
#     - workflow
jobs:
  deployment:
    if: github.actor == 'SadanandGowda' || github.actor ==  'AbhiGaddi' || github.actor == 'shiva-rakshith'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Checkout private
        uses: actions/checkout@v3
        with:
          # repository: Swasth-Digital-Health-Foundation/DevOps
          repository: Swasth-Digital-Health-Foundation/DevOps
          ref: 'workflow'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive
          path: DevOps

      - name: Pull image tag from S3 bucket
        run: |
          aws s3 cp s3://build-tags/tag.txt /tmp/tag.txt
          cat /tmp/tag.txt

      - name: Set an environment variable from a file
        # run: env MY_VARIABLE="$(cat /tmp/tag.txt)"
        run: echo "IMAGE_TAG=$(cat /tmp/tag.txt)" >> $GITHUB_ENV

      - name: Uninstall previous flink job
        uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          action: uninstall
          cluster-name: ${{ github.event.inputs.environment }}-cluster
          namespace: 'flink'
          name: 'notificationjob'

      - name: 'Deploy'
        uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
        # uses: vimeda/helm@v1.6.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # cluster-role-arn: arn:aws:iam::131795456882:user/hcx
          aws-region: ap-south-1
          # aws-profile: git-deploy
          cluster-name: ${{ github.event.inputs.environment }}-cluster
          name: 'notificationjob'
          namespace: 'flink'
          chart-path: 'application/helm/flink/notificationjob/'
          config-files: 'application/helm/flink/notificationjob/values.yaml, DevOps/hcx/ansible/inventory/${{ github.event.inputs.environment }}/group_vars/${{ github.event.inputs.environment }}.yaml, DevOps/hcx/ansible/inventory/${{ github.event.inputs.environment }}/group_vars/config-flink.yaml' #, https://github.com/Swasth-Digital-Health-Foundation/DevOps/blob/workflow/hcx/ansible/inventory/${{ github.event.inputs.environment }}/group_vars/${{ github.event.inputs.environment }}.yaml'
          # token: '${{ github.token }}'
          values: |
            image.tag=${{ env.IMAGE_TAG }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'


