name: Deploy workflow for Superset
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Cluster Environment
        default: dev
        required: true
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Checkout private
        uses: actions/checkout@v3
        with:
          # repository: Swasth-Digital-Health-Foundation/DevOps
          repository: Swasth-Digital-Health-Foundation/DevOps
          ref: 'workflow'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive
          path: DevOps


      - name: 'Deploy'
        uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
        # uses: vimeda/helm@v1.6.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # cluster-role-arn: arn:aws:iam::131795456882:user/hcx
          aws-region: ap-south-1
          # aws-profile: git-deploy
          cluster-name: ${{ github.event.inputs.environment }}-cluster
          name: 'superset'
          namespace: ${{ github.event.inputs.environment }}
          # release: superset
          chart-path: 'application/helm/core/superset/'
          config-files: 'application/helm/core/superset/values.yaml, DevOps/hcx/ansible/inventory/${{ github.event.inputs.environment }}/group_vars/${{ github.event.inputs.environment }}.yaml' #, https://github.com/Swasth-Digital-Health-Foundation/DevOps/blob/workflow/hcx/ansible/inventory/${{ github.event.inputs.environment }}/group_vars/${{ github.event.inputs.environment }}.yaml'
          # values: |
          #   image:
          #     tag: env.IMAGE_TAG
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

###

