name: Deploy workflow on Test2
on:
  workflow_dispatch:
    inputs:
      Environment_Name:
        description: 'Deploy Environment'
        required: true
        default: 'staging'
      namespace:
        description: 'Deploy Environment'
        required : true
        default: 'staging'
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-2








    - name: Checkout private 
      uses: actions/checkout@v3
      with:
        # repository: Swasth-Digital-Health-Foundation/DevOps
        repository: Swasth-Digital-Health-Foundation/DevOps
        ref: 'workflow'
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive
        path: DevOps


    - name: Cat private repo file
      run: cat ${{ github.workspace }}/DevOps/hcx/ansible/inventory/dev/group_vars/dev.yaml
      



###


